apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-service
  template:
    metadata:
      labels:
        app: administration-service
    spec:
      #imagePullSecrets:
      #- name: dockersecret
      containers:
      - name: administration-service
        image: jpcallerani/administration-service:latest
        ports:
        - containerPort: 8060
   
---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
  labels:
    app: administration-service
spec:
  type: ClusterIP
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8060
      targetPort: 8060
  selector:
    app: administration-service

